package uz.gita.weatherappbyxr.database.models.geo_code

import com.google.gson.annotations.SerializedName

data class LocalNames (
    val cv:String,
    val tg:String,
    val pt:String,
    val mr:String,
    val ml:String,
    val af:String,
    val ga:String,
    val lo:String,
    val en:String,
    val tl:String,
    val ky:String,
    val yi:String,
    val li:String,
    val nl:String,
    @SerializedName("is")
    val iss:String,
    val fr:String,
    val tt:String,
    val lt:String,
    val hy:String,
    val de:String,
    val or:String,
    val cs:String,
    val zu:String,
    val bn:String,
    val lv:String,
    val sl:String,
    val sv:String,
    val feature_name: String,
    val ln: String,
    val fa: String,
    val gn: String,
    val ko: String,
    val te: String,
    val bo: String,
    val kn: String,
    val he: String,
    val mi: String,
    val cu: String,
    val vi: String,
    val cy: String,
    val rm: String,
    val eu: String,
    val ne: String,
    val fy: String,
    val sr: String,
    val uk: String,
    val eo: String,
    val yo: String,
    val fi: String,
    val ro: String,
    val kk: String,
    val ka: String,
    val oc: String,
    val gd: String,
    val pl: String,
    val gu: String,
    val mn: String,
    val mt: String,
    val an: String,
    val sa: String,
    val sq: String,
    val kw: String,
    val gl: String,
    val ascii: String,
    val hi: String,
    val bg: String,
    val ba: String,
    val gv: String,
    val el: String,
    val br: String,
    val ab: String,
    val be: String,
    val ht: String,
    val sc: String,
    val zh: String,
    val it: String,
    val es: String,
    val os: String,
    val hu: String,
    val th: String,
    val et: String,
    val am: String,
    val ca: String,
    val sk: String,
    val ru: String,
    val ja: String,
    val ta: String,
    val ar: String,
    val si: String,
    val ur: String,
    val no: String,
    val wo: String,
    val co: String,
    val mk: String,
    val ps: String,
    val my: String,
    val kv: String,
    val tr: String,
    val ku: String,

)
